/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsWorkspacesRouteImport } from './routes/settings/workspaces'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsChatRouteImport } from './routes/settings/chat'
import { Route as AppCodeReviewRouteRouteImport } from './routes/_app/code-review/route'
import { Route as AppCodeReviewIndexRouteImport } from './routes/_app/code-review/index'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents/index'
import { Route as SettingsWorkspaceWorkspaceIdRouteImport } from './routes/settings/workspace/$workspaceId'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app/agents/$agentId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsWorkspacesRoute = SettingsWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsChatRoute = SettingsChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const AppCodeReviewRouteRoute = AppCodeReviewRouteRouteImport.update({
  id: '/code-review',
  path: '/code-review',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCodeReviewIndexRoute = AppCodeReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCodeReviewRouteRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRouteRoute,
} as any)
const SettingsWorkspaceWorkspaceIdRoute =
  SettingsWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/code-review': typeof AppCodeReviewRouteRouteWithChildren
  '/settings/chat': typeof SettingsChatRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/settings/': typeof SettingsIndexRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/settings/workspace/$workspaceId': typeof SettingsWorkspaceWorkspaceIdRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/code-review/': typeof AppCodeReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/settings': typeof SettingsIndexRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/settings/workspace/$workspaceId': typeof SettingsWorkspaceWorkspaceIdRoute
  '/agents': typeof AppAgentsIndexRoute
  '/code-review': typeof AppCodeReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/code-review': typeof AppCodeReviewRouteRouteWithChildren
  '/settings/chat': typeof SettingsChatRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/settings/': typeof SettingsIndexRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/settings/workspace/$workspaceId': typeof SettingsWorkspaceWorkspaceIdRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/code-review/': typeof AppCodeReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/onboarding'
    | '/code-review'
    | '/settings/chat'
    | '/settings/notifications'
    | '/settings/workspaces'
    | '/settings/'
    | '/agents/$agentId'
    | '/settings/workspace/$workspaceId'
    | '/agents/'
    | '/code-review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/settings/chat'
    | '/settings/notifications'
    | '/settings/workspaces'
    | '/settings'
    | '/agents/$agentId'
    | '/settings/workspace/$workspaceId'
    | '/agents'
    | '/code-review'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/settings'
    | '/onboarding'
    | '/_app/code-review'
    | '/settings/chat'
    | '/settings/notifications'
    | '/settings/workspaces'
    | '/settings/'
    | '/_app/agents/$agentId'
    | '/settings/workspace/$workspaceId'
    | '/_app/agents/'
    | '/_app/code-review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/workspaces': {
      id: '/settings/workspaces'
      path: '/workspaces'
      fullPath: '/settings/workspaces'
      preLoaderRoute: typeof SettingsWorkspacesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/chat': {
      id: '/settings/chat'
      path: '/chat'
      fullPath: '/settings/chat'
      preLoaderRoute: typeof SettingsChatRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_app/code-review': {
      id: '/_app/code-review'
      path: '/code-review'
      fullPath: '/code-review'
      preLoaderRoute: typeof AppCodeReviewRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/code-review/': {
      id: '/_app/code-review/'
      path: '/'
      fullPath: '/code-review/'
      preLoaderRoute: typeof AppCodeReviewIndexRouteImport
      parentRoute: typeof AppCodeReviewRouteRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/settings/workspace/$workspaceId': {
      id: '/settings/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/settings/workspace/$workspaceId'
      preLoaderRoute: typeof SettingsWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppCodeReviewRouteRouteChildren {
  AppCodeReviewIndexRoute: typeof AppCodeReviewIndexRoute
}

const AppCodeReviewRouteRouteChildren: AppCodeReviewRouteRouteChildren = {
  AppCodeReviewIndexRoute: AppCodeReviewIndexRoute,
}

const AppCodeReviewRouteRouteWithChildren =
  AppCodeReviewRouteRoute._addFileChildren(AppCodeReviewRouteRouteChildren)

interface AppRouteRouteChildren {
  AppCodeReviewRouteRoute: typeof AppCodeReviewRouteRouteWithChildren
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCodeReviewRouteRoute: AppCodeReviewRouteRouteWithChildren,
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsChatRoute: typeof SettingsChatRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsWorkspacesRoute: typeof SettingsWorkspacesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsWorkspaceWorkspaceIdRoute: typeof SettingsWorkspaceWorkspaceIdRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsChatRoute: SettingsChatRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsWorkspacesRoute: SettingsWorkspacesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsWorkspaceWorkspaceIdRoute: SettingsWorkspaceWorkspaceIdRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
